package ru.ildarka.pages;/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.net.URISyntaxException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * @author Ildar
 */
class Records extends javax.swing.JFrame {

    /**
     * Creates new form Records
     */
    public Records() {
        initComponents();
        setBounds(300, 60, 640, 640);
        setResizable(false);
        try {
            File file = new File(getClass().getResource("/Record.txt").toURI());
            FileReader fr = new FileReader(file);
            Scanner sc = new Scanner(fr);
            if (sc.hasNext()) {
                jLabel2.setText(sc.nextLine());
            }
            if (sc.hasNext()) {
                jLabel3.setText(sc.nextLine());
            }
            if (sc.hasNext()) {
                jLabel4.setText(sc.nextLine());
            }
            if (sc.hasNext()) {
                jLabel5.setText(sc.nextLine());
            }
            if (sc.hasNext()) {
                jLabel6.setText(sc.nextLine());
            }
        } catch (FileNotFoundException | URISyntaxException ex) {
            Logger.getLogger(Records.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        java.awt.Label label1 = new java.awt.Label();
        javax.swing.JTextField jTextField1 = new javax.swing.JTextField();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JButton jButton2 = new javax.swing.JButton();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();

        label1.setText("label1");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(300, 60, 640, 640));
        setLocation(new java.awt.Point(300, 60));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" RECORDS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 20, 367, 100);

        jLabel2.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(108, 133, 220, 36);

        jLabel3.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(108, 213, 220, 36);

        jLabel4.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(108, 298, 220, 36);

        jLabel5.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(108, 386, 220, 36);

        jLabel6.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(108, 473, 220, 38);

        jButton2.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 36)); // NOI18N
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 520, 201, 66);

        jLabel7.setFont(new java.awt.Font("Tahoma", Font.BOLD, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("   1");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(22, 117, 68, 69);

        jLabel12.setFont(new java.awt.Font("Tahoma", Font.BOLD, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("   3");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(22, 279, 68, 69);

        jLabel13.setFont(new java.awt.Font("Tahoma", Font.BOLD, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("   2");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(22, 192, 68, 69);

        jLabel14.setFont(new java.awt.Font("Tahoma", Font.BOLD, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("   4");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(22, 366, 68, 69);

        jLabel15.setFont(new java.awt.Font("Tahoma", Font.BOLD, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("   5");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(22, 453, 68, 69);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 0, 640);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 640, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());


                    break;

                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(Records.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Records().setVisible(true);
            }
        });
    }

    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
